### ISSUE TITLE
BUG: RangeError: invalid array length

### ISSUE THREAD

**Issue by kesylo** [farhoudshapouran/react-native-ui-datepicker#28] opened 2023-10-31 23:34 UTC
Thanks for the quick fix but it caused another issue I think. Now this is what I get

![image](https://github.com/farhoudshapouran/react-native-ui-datepicker/assets/32457792/0f918f54-8f2f-4c07-a422-703b9cf7be5d)

I used your latest fix 1.0.6

_Originally posted by @kesylo in https://github.com/farhoudshapouran/react-native-ui-datepicker/issues/24#issuecomment-1788175236_

**Comment by farhoudshapouran** [comment] 2023-11-01 06:56
Yes, this is about all arrays that have the possibility of being undefined, I tried to fix all of them, please use the latest version and let me know if the problem exists yet

**Comment by kesylo** [comment] 2023-11-01 12:31
Hey @farhoudshapouran 
Sorry but still crashes

![image](https://github.com/farhoudshapouran/react-native-ui-datepicker/assets/32457792/ccfa50f1-3c2d-4416-bd70-e49bdce39b77)

**Comment by farhoudshapouran** [comment] 2023-11-01 14:52
I think the usage of utils class made this error, I changed the usage of it please update the library and check again, I checked it with all modes: `datetime`, `date`, and `time`

**Comment by kesylo** [comment] 2023-11-01 18:48
Dont know what is happening, but I have the exact same issue on 1.0.8. I will try to test on a brand new expo project to see

**Comment by farhoudshapouran** [comment] 2023-11-13 10:22
After a thorough investigation, I was unable to reproduce the reported error. I have attempted to recreate the steps outlined in the issue description, but the issue did not manifest in the testing environment. 

If you encounter the issue again or have additional information, please reopen the issue.

I have to close this issue as 'Not Planned' for now.

**Closed** 2023-11-13 10:22 UTC

**Comment by asraful0106** [comment] 2026-01-14 13:18
When passing:

 const [slectedDate, setSlectedDate] = useState<DateType>(null);
<DateTimePicker
              mode="single"
              date={slectedDate}
              onChange={({ date }) => setSlectedDate(date)}
              styles={customStyles}
              minDate={new Date()}
            />

will re-create the bug. A quick fix for my case is:
const [slectedDate, setSlectedDate] = useState<DateType>(new Date());

### But the problem I think is (not 100% sure): 
const prevMonthOffset = firstDay.day() % 7;

This line ignores firstDayOfWeek completely. So when your week is not Sunday-first, the grid math becomes inconsistent and later the component ends up calling Array(prevMonthOffset) with a bad value in some months/configs (your screenshot shows it blowing up exactly there).

Minimal fix:
const prevMonthOffset = (firstDay.day() - firstDayOfWeek + 7) % 7;
